volumes:
  staticfiles:
  mediafiles:
  pg_data:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: rmv9/foodgram_backend
    volumes:
      - staticfiles:/app/staticfiles/
      - mediafiles:/app/media/
    env_file: .env
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: rmv9/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - staticfiles:/frontend_static

  nginx:
    container_name: foodgram-proxy
    image: rmv9/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - staticfiles:/staticfiles/
      - mediafiles:/media/
    depends_on:
      - frontend
      - backend