# Generated by Django 4.2.11 on 2024-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkMapped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_hash", models.CharField(max_length=10)),
                ("original_url", models.URLField()),
            ],
        ),
    ]
