# Generated by Django 4.2.11 on 2024-04-30 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0004_alter_linkmapped_url_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkmapped",
            options={"verbose_name": "Ссылка", "verbose_name_plural": "Ссылки"},
        ),
    ]
