# Generated by Django 4.2.11 on 2024-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_alter_favoriterecipe_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={
                'ordering': ('name',),
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
