# Generated by Django 4.2.11 on 2024-05-07 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'default_related_name': 'recipes',
                'ordering': ('-created_at',),
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
