# Generated by Django 4.2.11 on 2024-04-30 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_subscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "default_related_name": "subscribers",
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
