# Generated by Django 4.2.11 on 2024-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_subscriber_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique_subscriber"
            ),
        ),
    ]
