# Generated by Django 4.2.11 on 2024-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_subscriber_unique_subscriber_himself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
